# Generated by Django 4.1.7 on 2023-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price_en',
            field=models.PositiveIntegerField(null=True, verbose_name='SubCategory price'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price_hy',
            field=models.PositiveIntegerField(null=True, verbose_name='SubCategory price'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='SubCategory price'),
        ),
    ]
