# Generated by Django 4.1.7 on 2023-04-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_name_en_category_name_hy_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price_hy',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price_ru',
        ),
    ]
